"""
Trace-driven FANET replay for AirSim trajectory logs.

This module reads the CSV generated by airsim_trajectory_logger.py and computes
FANET topology and packet metrics from real AirSim positions. It can also consume
any CSV matching the same schema.

Expected CSV columns:
time_s,sequence,node_id,x_m,y_m,z_m,vx_mps,vy_mps,vz_mps,source
"""
from __future__ import annotations

import argparse
import csv
import math
import random
from collections import defaultdict, deque
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path
from statistics import mean, pstdev
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


@dataclass(frozen=True)
class TraceState:
    time_s: float
    sequence: int
    node_id: str
    x_m: float
    y_m: float
    z_m: float


@dataclass
class ReplayMetrics:
    trace_file: str
    source: str
    num_uavs: int
    samples: int
    duration_s: float
    sample_rate_hz: float
    communication_range_m: float
    packet_attempts: int
    delivered_packets: int
    pdr: float
    mean_latency_ms: float
    std_latency_ms: float
    mean_hops: float
    topology_changes_per_s: float
    mean_link_lifetime_s: float
    throughput_packets_s: float


def load_trace(path: Path) -> Dict[int, List[TraceState]]:
    by_sequence: Dict[int, List[TraceState]] = defaultdict(list)
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {"time_s", "sequence", "node_id", "x_m", "y_m", "z_m"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required CSV columns: {sorted(missing)}")
        for row in reader:
            state = TraceState(
                time_s=float(row["time_s"]),
                sequence=int(row["sequence"]),
                node_id=str(row["node_id"]),
                x_m=float(row["x_m"]),
                y_m=float(row["y_m"]),
                z_m=float(row["z_m"]),
            )
            by_sequence[state.sequence].append(state)
    if not by_sequence:
        raise ValueError("Trace file contains no samples.")
    return dict(sorted(by_sequence.items()))


def distance(a: TraceState, b: TraceState) -> float:
    return math.sqrt((a.x_m - b.x_m) ** 2 + (a.y_m - b.y_m) ** 2 + (a.z_m - b.z_m) ** 2)


def compute_edges(states: Sequence[TraceState], communication_range_m: float) -> set[Tuple[str, str]]:
    edges: set[Tuple[str, str]] = set()
    for a, b in combinations(states, 2):
        if distance(a, b) <= communication_range_m:
            edges.add(tuple(sorted((a.node_id, b.node_id))))
    return edges


def shortest_path_hops(src: str, dst: str, edges: Iterable[Tuple[str, str]]) -> Optional[int]:
    graph: Dict[str, List[str]] = defaultdict(list)
    for a, b in edges:
        graph[a].append(b)
        graph[b].append(a)
    queue = deque([(src, 0)])
    seen = {src}
    while queue:
        node, hops = queue.popleft()
        if node == dst:
            return hops
        for nxt in graph[node]:
            if nxt not in seen:
                seen.add(nxt)
                queue.append((nxt, hops + 1))
    return None


def replay_trace(
    trace_file: Path,
    communication_range_m: float = 35.0,
    packets_per_sample: int = 5,
    seed: int = 123,
) -> ReplayMetrics:
    rng = random.Random(seed)
    by_sequence = load_trace(trace_file)
    sequences = sorted(by_sequence)
    node_ids = sorted({s.node_id for states in by_sequence.values() for s in states})
    first_time = min(s.time_s for s in by_sequence[sequences[0]])
    last_time = max(s.time_s for s in by_sequence[sequences[-1]])
    duration = max(last_time - first_time, 1e-9)
    sample_rate = len(sequences) / duration

    prev_edges: set[Tuple[str, str]] = set()
    edge_start: Dict[Tuple[str, str], float] = {}
    lifetimes: List[float] = []
    topology_changes = 0
    attempts = 0
    delivered = 0
    latencies: List[float] = []
    hops_values: List[int] = []

    for seq in sequences:
        states = by_sequence[seq]
        current_time = mean([s.time_s for s in states])
        edges = compute_edges(states, communication_range_m)
        topology_changes += len(edges.symmetric_difference(prev_edges))

        for edge in edges - prev_edges:
            edge_start[edge] = current_time
        for edge in prev_edges - edges:
            if edge in edge_start:
                lifetimes.append(current_time - edge_start.pop(edge))

        if len(node_ids) >= 2:
            for _ in range(packets_per_sample):
                src, dst = rng.sample(node_ids, 2)
                attempts += 1
                hops = shortest_path_hops(src, dst, edges)
                if hops is not None and hops > 0:
                    delivered += 1
                    latency = 8.0 + 4.5 * hops + rng.uniform(0.0, 3.0)
                    latencies.append(latency)
                    hops_values.append(hops)
        prev_edges = edges

    # Close links active at the end of the trace.
    for edge, start_time in edge_start.items():
        lifetimes.append(last_time - start_time)

    source_values = []
    with trace_file.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if "source" in (reader.fieldnames or []):
            source_values = [row.get("source", "trace") for row in reader]
    source = sorted(set(source_values))[0] if source_values else "trace"

    return ReplayMetrics(
        trace_file=str(trace_file),
        source=source,
        num_uavs=len(node_ids),
        samples=len(sequences),
        duration_s=duration,
        sample_rate_hz=sample_rate,
        communication_range_m=communication_range_m,
        packet_attempts=attempts,
        delivered_packets=delivered,
        pdr=delivered / attempts if attempts else 0.0,
        mean_latency_ms=mean(latencies) if latencies else 0.0,
        std_latency_ms=pstdev(latencies) if len(latencies) > 1 else 0.0,
        mean_hops=mean(hops_values) if hops_values else 0.0,
        topology_changes_per_s=topology_changes / duration,
        mean_link_lifetime_s=mean(lifetimes) if lifetimes else 0.0,
        throughput_packets_s=delivered / duration,
    )


def write_metrics(metrics: ReplayMetrics, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(metrics.__dataclass_fields__.keys())
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerow({k: getattr(metrics, k) for k in fieldnames})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Replay AirSim trajectory CSV logs through FANET topology analysis.")
    parser.add_argument("--trace", type=Path, required=True, help="AirSim trajectory CSV path")
    parser.add_argument("--range", type=float, default=35.0, help="Communication range in meters")
    parser.add_argument("--packets-per-sample", type=int, default=5, help="Packet attempts per sampled time step")
    parser.add_argument("--seed", type=int, default=123, help="Random seed for source-destination sampling")
    parser.add_argument("--out", type=Path, default=Path("airsim_fanet_replay_metrics.csv"), help="Output metrics CSV")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    metrics = replay_trace(args.trace, args.range, args.packets_per_sample, args.seed)
    write_metrics(metrics, args.out)
    print(metrics)
